version: '3'
services:

#Default Administrator User
#Email: admin@example.com
#Password: changeme

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
#     - '80:80'
      - '81:81'
      - '443:443'
    environment:
      - DISABLE_IPV6='true'
    volumes:
      - ./docker/proxy/data:/data
      - ./docker/proxy/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    networks:
      docker-servicios:
        ipv4_address: 192.168.254.2

networks:
  docker-servicios:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.254.0/24