CREATE USER zabbix WITH PASSWORD 'Abcd1234';
CREATE USER netbox WITH PASSWORD 'Abcd1234';

CREATE DATABASE zabbixdb WITH OWNER zabbix;
CREATE DATABASE netboxdb WITH OWNER netbox;

GRANT ALL PRIVILEGES ON DATABASE zabbixdb, netboxdb TO user1;
GRANT ALL PRIVILEGES ON DATABASE zabbixdb, netboxdb TO user2;