#Servidor de Monitoreo

version: '3.9'
services:

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    ports:
#      - '80:80'
#      - '81:81'
      - '443:443'
    environment:
      - DISABLE_IPV6=true
    volumes:
      - ./docker/proxy/data:/data
      - ./docker/proxy/letsencrypt:/etc/letsencrypt
    networks:
      docker-servicios:
        ipv4_address: 192.168.255.2
    restart: unless-stopped

  agent:
    image: 'portainer/agent:latest'
    container_name: portainer_agent
    volumes:
      - '/var/lib/docker/volumes:/var/lib/docker/volumes'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '9001:9001'
    networks:
      docker-servicios:
        ipv4_address: 192.168.255.3
    restart: unless-stopped

networks:
  docker-servicios:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 192.168.255.0/24
    driver_opts:
      com.docker.network.bridge.name: BR-Monitoreo